DROP TABLE IF EXISTS CA_USER;
CREATE TABLE CA_USER (
	ID serial PRIMARY KEY,
	NAME VARCHAR (255) NOT NULL,
	EMAIL VARCHAR (255) UNIQUE NOT NULL,
	GRADE VARCHAR (10) NOT NULL,
	DESIGNATION VARCHAR (255) NOT NULL
);